src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this e-mail address")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=191, nullable=true, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $language;

    /**
     * @ORM\Column(type="boolean")
     */
    private $member;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastEmail;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Bet::class, mappedBy="user")
     */
    private $bets;

    /**
     * @ORM\OneToMany(targetEntity=Game::class, mappedBy="createdBy")
     */
    private $gamesAdded;

    /**
     * @ORM\OneToMany(targetEntity=Game::class, mappedBy="updatedBy")
     */
    private $gamesUpdated;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $locale = "pl";

    /**
     * @ORM\OneToMany(targetEntity=Classification::class, mappedBy="user", orphanRemoval=true)
     */
    private $classifications;

    public function __construct()
    {
        $this->bets            = new ArrayCollection();
        $this->gamesAdded      = new ArrayCollection();
        $this->gamesUpdated    = new ArrayCollection();
        $this->classifications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getMember(): ?bool
    {
        return $this->member;
    }

    public function setMember(bool $member): self
    {
        $this->member = $member;

        return $this;
    }

    public function getLastEmail(): ?string
    {
        return $this->lastEmail;
    }

    public function setLastEmail(?string $lastEmail): self
    {
        $this->lastEmail = $lastEmail;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Bet[]
     */
    public function getBets(): Collection
    {
        return $this->bets;
    }

    public function addBet(Bet $bet): self
    {
        if (!$this->bets->contains($bet)) {
            $this->bets[] = $bet;
            $bet->setUser($this);
        }

        return $this;
    }

    public function removeBet(Bet $bet): self
    {
        if ($this->bets->removeElement($bet)) {
            // set the owning side to null (unless already changed)
            if ($bet->getUser() === $this) {
                $bet->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGamesAdded(): Collection
    {
        return $this->gamesAdded;
    }

    public function addGamesAdded(Game $gamesAdded): self
    {
        if (!$this->gamesAdded->contains($gamesAdded)) {
            $this->gamesAdded[] = $gamesAdded;
            $gamesAdded->setCreatedBy($this);
        }

        return $this;
    }

    public function removeGamesAdded(Game $gamesAdded): self
    {
        if ($this->gamesAdded->removeElement($gamesAdded)) {
            // set the owning side to null (unless already changed)
            if ($gamesAdded->getCreatedBy() === $this) {
                $gamesAdded->setCreatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGamesUpdated(): Collection
    {
        return $this->gamesUpdated;
    }

    public function addGamesUpdated(Game $gamesUpdated): self
    {
        if (!$this->gamesUpdated->contains($gamesUpdated)) {
            $this->gamesUpdated[] = $gamesUpdated;
            $gamesUpdated->setUpdatedBy($this);
        }

        return $this;
    }

    public function removeGamesUpdated(Game $gamesUpdated): self
    {
        if ($this->gamesUpdated->removeElement($gamesUpdated)) {
            // set the owning side to null (unless already changed)
            if ($gamesUpdated->getUpdatedBy() === $this) {
                $gamesUpdated->setUpdatedBy(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return Collection|Classification[]
     */
    public function getClassifications(): Collection
    {
        return $this->classifications;
    }

    public function addClassification(Classification $classification): self
    {
        if (!$this->classifications->contains($classification)) {
            $this->classifications[] = $classification;
            $classification->setUser($this);
        }

        return $this;
    }

    public function removeClassification(Classification $classification): self
    {
        if ($this->classifications->removeElement($classification)) {
            // set the owning side to null (unless already changed)
            if ($classification->getUser() === $this) {
                $classification->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Service\BetService;
use App\Service\UserService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="users_list")
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function index(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $users = $em->getRepository(User::class)->findAll();

        return $this->render('user/users_list.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/user/{username}", name="user_info")
     * @param User $user
     * @param BetService $betService
     * @return Response
     * @IsGranted("ROLE_USER")
     */
    public function user_info(User $user, BetService $betService, UserService $userService): Response
    {
        return $this->render('user/user_info.html.twig', [
            'user' => $user,
            'bets' => $betService->calcUserBets($user),
            'rankings' => $userService->getRankings($user),
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Mensański Typer</li>
                        <li class="breadcrumb-item" aria-current="page">{{ 'breadcump.user'|trans }}</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="row">
            {% if user is defined %}
                {% include 'user/_partials/left_column.html.twig' %}
            {% endif %}
            <div class="col-lg-9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/user_info.html.twig
{% extends 'user/index.html.twig' %}

{% block title %}User - {{ parent() }}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            {{ 'card.summary'|trans }}
        </div>
        <div class="card-body">
            <div class="d-flex align-items-center">
                <div class="flex-shrink-0 item-logo">
                    {% set sex = user.firstName|last == 'a' ? 'female' : 'male' %}
                    <img class="mx-5 my-3 user-profile-img" src="{{ asset('assets/img/' ~ sex ~ '.png') }}" alt="{{ sex }}">
                </div>
                <div class="flex-grow-1 ms-3">
                    <table class="table table-sm">
                        <tbody>
                        <tr>
                            <td class="fs-4 fw-mid" width="30%" colspan="2">
                                {{ user.fullName }}
                            </td>
                        </tr>
                        {% if bets.amount != 0 %}
                            <tr>
                                <td width="30%">
                                    {{ 'user.competitions'|trans }}:
                                </td>
                                <td class="text-center">
                                    <span class="fw-mid">{{ user.classifications|length }}</span>
                                </td>
                            </tr>
                            <tr>
                                <td width="30%">
                                    {{ 'user.predictedMatches'|trans }}:
                                </td>
                                <td class="text-center">
                                    <span class="fw-mid">{{ bets.amount }}</span>
                                </td>
                            </tr>
                            <tr>
                                <td width="30%">
                                    {{ 'user.typingSuccess'|trans }}:
                                </td>
                                <td class="text-center">
                                    <span class="fw-mid">{{ bets.good }}</span>
                                    <small>{{ ((bets.good/bets.amount)*100)|number_format(1) }}%</small>
                                </td>
                            </tr>
                            <tr>
                                <td width="30%">
                                    {{ 'user.exactHits'|trans }}:
                                </td>
                                <td class="text-center">
                                    <span class="fw-mid">{{ bets.hits }}</span>
                                    <small>{{ ((bets.hits/bets.amount)*100)|number_format(1) }}%</small>
                                </td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                    {% if bets.amount == 0 %}
                        {{ 'user.passive'|trans }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% if rankings is not empty %}
        {% if rankings.current is not empty %}
            <div class="card">
                <div class="card-header">
                    {{ 'card.currentRankings'|trans }}
                </div>
                <div class="card-body">
                    {% for classification in rankings.current %}
                        <div class="d-flex align-items-center mb-3">
                            <div class="flex-shrink-0 item-logo">
                                <img class="mx-5 my-3 user-profile-img" src="" alt="">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <table class="table table-sm">
                                    <tbody>
                                    <tr>
                                        <td class="fs-4 fw-mid" width="30%" colspan="2">
                                            {{ classification.ranking.name }}
                                        </td>
                                    </tr>
                                    {% if bets.amount != 0 %}
                                        <tr>
                                            <td width="30%">
                                                {{ 'ranking.position'|trans }}:
                                            </td>
                                            <td class="text-center">
                                                <span class="fs-5 fw-mid">{{ classification.place }}</span>
                                                <small>/{{ classification.ranking.classifications|length }}</small>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="30%">
                                                {{ 'ranking.points'|trans }}:
                                            </td>
                                            <td class="text-center">
                                                <span class="fw-mid">{{ classification.pts }} {{ 'game.points'|trans }}</span>
                                                <small>{{ 'ranking.averagePerGame'|trans({'%pts%': (classification.pts/classification.typedGames)|number_format(2)}) }}</small>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="30%">
                                                {{ 'user.typingSuccess'|trans }}:
                                            </td>
                                            <td class="text-center">
                                                <span class="fw-mid">{{ classification.scored }}</span>
                                                <small>/{{ classification.typedGames }}</small>
                                                <small>{{ (classification.scored / classification.typedGames * 100)|number_format(1) }}%
                                                </small>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td width="30%">
                                                {{ 'user.exactHits'|trans }}:
                                            </td>
                                            <td class="text-center">
                                                <span class="fw-mid">{{ classification.hits }}</span>
                                                <small>/{{ classification.typedGames }}</small>
                                                <small>{{ (classification.hits / classification.typedGames * 100)|number_format(1) }}%
                                                </small>
                                            </td>
                                        </tr>
                                    {% endif %}
                                    </tbody>
                                </table>
                                {% if bets.amount == 0 %}
                                    {{ 'user.passive'|trans }}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if rankings.finished is not empty %}
            <div class="card">
                <div class="card-header">
                    {{ 'card.finishedRankings'|trans }}
                </div>
                <div class="card-body">
                    <table class="table table-sm">
                        <thead class="table-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col" class="text-center">{{ 'ranking.position'|trans }}</th>
                            <th scope="col" class="text-center">{{ 'ranking.points'|trans }}</th>
                            <th scope="col" class="text-center">{{ 'ranking.effectiveness'|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for classification in rankings.finished %}
                            <tr class="row-link" data-href="{{ path('ranking_detail', {'slug': classification.ranking.slug}) }}">
                                <td>
                                    {{ loop.index }}
                                </td>
                                <td class="fw-mid">
                                    {{ classification.ranking.name }}
                                </td>
                                <td class="text-center">

                                </td>
                                <td class="text-center">
                                    <span class="fs-normal fw-mid">{{ classification.place }}</span>
                                    <small>/{{ classification.ranking.classifications|length }}</small>
                                </td>
                                <td class="fw-mid text-center">
                                    {{ classification.pts }} {{ 'game.points'|trans }}
                                </td>
                                <td class="text-center">
                                    {{ (classification.scored / classification.typedGames * 100)|number_format(1) }}%
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/user/users_list.html.twig
{% extends 'user/index.html.twig' %}

{% block title %}User list - {{ parent() }}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            {{ 'user.list'|trans }}
        </div>
        <div class="card-body">
            {% for user in users %}
                <a href="{{ path('user_info', {'username': user.username}) }}">{{ user.fullName }}</a><br/>
            {% endfor %}
        </div>
    </div>
{% endblock %}